### PR TITLE
add separate provider config support

### PR DESCRIPTION
**Pull request by parrasajad**

### CODE REVIEW

**Comment by ehsandeep** [comment]
@parrasajad tried and failed with the following config and command.

config:- `test.yaml`

```yaml
discord:
  - profile: test
    discord_webhook_url: https://discord.com/api/webhooks/XX/XX
    discord_username: test
    discord_channel: notify-test
```

```
echo test | ./notify -provider-config test.yaml
echo test | ./notify -provider-config test.yaml -profile test
```

**Review by Mzack9999 — APPROVED** [review]

**Comment by Mzack9999** [comment]
LGTM!

**Comment by ehsandeep** [comment]
Some conflict issue with the existing config file `~/.config/notify/config.yaml `, it works for me after removing this file.

**Review by ehsandeep — APPROVED** [review]

**Comment by Regala** [comment]
Possible bug, assuming the default providers config in `~/.config/notify/provider-config.yaml`

`rm ~/.config/notify/config.yaml`
`echo 'hello' | notify -profile notify` -> works
`echo 'hello2' | notify -profile notify` -> doesn't work

On the second run `~/.config/notify/config.yaml` was automatically generated so `~/.config/notify/provider-config.yaml` is not read. 

Even doing 
`echo 'hello' | notify -profile notify -provider-config ~/.config/notify/provider-config.yaml` will not work.

**Pull request merged**
