### PR TITLE
feat: Message format as golang template

### PR DESCRIPTION
**Pull request by NoF0rte**
The message format is now a golang text template with access to the Sprig template functions.

Using the default format `{{.Data}}` will have the same outcome as the previous functionality.

This is an example of a Discord configuration:
```yaml
discord:
  - id: "interactsh"
    discord_format: |
      {{$data := fromJson .Data}}{{$raw := index $data "raw-request"}}{{$remote := index $data "remote-address"}}
      Remote IP: {{$remote}}
      
      {{$raw}}
```

### CODE REVIEW

**Review by fopinappb — COMMENTED** [review]
I think using go templates (and sprig) should be the default in every templated variable!

maybe for retro-compatibility it'd be nice to add some

```
if {{data}} in format {
deprecationWarning("update your config to use {{.Data}} instead of {{data}} as latter is deprecated")
msg = strings.replace(msg, "{{data}}","{{.Data}}")
}
```

**Comment by Mzack9999** [comment]
Closing as not planned (dot prefixed variable names are a breaking change) - CC @ehsandeep

**Comment by fopina** [comment]
> Closing as not planned (dot prefixed variable names are a breaking change) - CC @ehsandeep

@Mzack9999 if a clean proposal allowing retro compatibility, would it be ok?
Something like I mentioned previously

**Comment by Mzack9999** [comment]
@fopina I'm reopening the PR for discussion

@ehsandeep Shall we add an automatic conversion layer? On a side I find the syntax `{{variable}}` cleaner than `{{.VariableName}}`

**Pull request closed without merging**
